// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(UCReviewsContext))]
    [Migration("20241007000129_SeedDormData")]
    partial class SeedDormData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Dorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameQueryParameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dorm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 3m,
                            Cost = "$",
                            Description = "Located in the heart of Clifton Heights, Calhoun Hall is known for its welcoming atmosphere and scenic views. Its community areas and study floor make it the perfect place to meet neighbors, cultivate friendships, and get involved in the UC community! The proximity to off- and on-campus dining options, as well as entertainment on Calhoun Street makes it an exciting and classic option when it comes to choosing where to live.",
                            Name = "Calhoun Hall",
                            NameQueryParameter = "Calhoun",
                            Style = "Traditional"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4m,
                            Cost = "$$$",
                            Description = "Campus Recreation Center Hall is perfect for students that desire productivity and focus in their day-to-day life. It is located on MainStreet connected to the Rec Center and CenterCourt dining hall, making it the perfect environment for motivation.",
                            Name = "CRC",
                            NameQueryParameter = "CRC",
                            Style = "Suite"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 2.9m,
                            Cost = "$",
                            Description = "This newly renovated hall fosters some of the strongest community on campus and puts you at the center of so much activity. Sitting in the middle of campus and just a short walk from the sprawling Sigma Sigma Commons.",
                            Name = "Dabney Hall",
                            NameQueryParameter = "Dabney",
                            Style = "Traditional"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 3m,
                            Cost = "$",
                            Description = "Daniels Hall most likely matches what comes to mind when you think of a college residence hall. Its traditional-style structure establishes a welcoming and very social atmosphere on every floor.",
                            Name = "Daniels Hall",
                            NameQueryParameter = "Daniels",
                            Style = "Traditional"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 4.5m,
                            Cost = "$$",
                            Description = "UC’s newest addition to University Housing and is a wonderful place for students to live. Its unique architecture allows for suite-style rooms.",
                            Name = "Marian Spencer",
                            NameQueryParameter = "Marian_Spencer",
                            Style = "Junior Suite"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 0m,
                            Cost = "$$$$",
                            Description = "Renovated in 2013, Morgens Hall was built as one of the Three Sisters and is now a state-of-the-art building with many awards for its eco-friendly design.",
                            Name = "Morgens Hall",
                            NameQueryParameter = "Morgens",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 0m,
                            Cost = "$$$",
                            Description = "Schneider Hall is in a wonderful part of eastern main campus along Jefferson Avenue, and is close to multiple dining centers, shops, and restaurants.",
                            Name = "Schneider Hall",
                            NameQueryParameter = "Schneider",
                            Style = "Suite"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 0m,
                            Cost = "$$$$",
                            Description = "Located close to multiple dining centers, Scioto Hall provides a spacious environment with suite-style living and plenty of community spaces.",
                            Name = "Scioto Hall",
                            NameQueryParameter = "Scioto",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 0m,
                            Cost = "$",
                            Description = "Siddall Hall includes the CCM themed community and is known for its communal activities such as ping pong tournaments and late-night ice cream parties.",
                            Name = "Siddall Hall",
                            NameQueryParameter = "Siddall",
                            Style = "Traditional"
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 0m,
                            Cost = "$$$$",
                            Description = "One of UC’s newest off-campus housing communities, The Deacon offers distinctive amenities such as a movie theater and arcade.",
                            Name = "The Deacon",
                            NameQueryParameter = "Deacon",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 0m,
                            Cost = "$$$$",
                            Description = "Newly constructed apartments just three blocks from campus, with floor plans and amenities ideal for building community among residents.",
                            Name = "The Eden",
                            NameQueryParameter = "Eden",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 0m,
                            Cost = "$$$",
                            Description = "Turner Hall is home to multiple Living-Learning Communities and has ADA accessible accommodations available.",
                            Name = "Turner Hall",
                            NameQueryParameter = "Turner",
                            Style = "Suite"
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 3.5m,
                            Cost = "$$$$",
                            Description = "University Edge apartments provide near-campus residency options with a sprawling courtyard and proximity to the Cincinnati Zoo.",
                            Name = "University Edge",
                            NameQueryParameter = "Edge",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 1m,
                            Cost = "$$$$",
                            Description = "University Park Apartments offer students an off-campus lifestyle with all the benefits of on-campus living, above many restaurants and shops.",
                            Name = "UPA",
                            NameQueryParameter = "UPA",
                            Style = "Apartment"
                        },
                        new
                        {
                            Id = 15,
                            AverageRating = 3.8m,
                            Cost = "$$$$",
                            Description = "Located on Calhoun Street, U Square provides apartment-style living with a relaxing and independent lifestyle while offering convenience to businesses.",
                            Name = "U Square",
                            NameQueryParameter = "USquare",
                            Style = "Apartment"
                        });
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DormId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DormId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordExpiration")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.HasOne("api.Models.Dorm", "Dorm")
                        .WithMany("Reviews")
                        .HasForeignKey("DormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dorm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Dorm", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
